export const CASH_CHECKOUT = "CASH_CHECKOUT";
export const CASH_CHECKOUT_SUCCESS = "CASH_CHECKOUT_SUCCESS";
export const CASH_CHECKOUT_FAILURE = "CASH_CHECKOUT_FAILURE";

//=================   visa checkout

export const VISA_CHECKOUT = "VISA_CHECKOUT";
export const VISA_CHECKOUT_SUCCESS = "VISA_CHECKOUT_SUCCESS";
export const VISA_CHECKOUT_FAILURE = "VISA_CHECKOUT_FAILURE";
