export const ADD_TO_WHISHLIST ="ADD_TO_WHISHLIST" 
export const ADD_TO_WHISHLIST_SUCCESS ="ADD_TO_WHISHLIST_SUCCESS" 
export const ADD_TO_WHISHLIST_FAILURE ="ADD_TO_WHISHLIST_FAILURE" 

//================================ DELETE WHISHLIST ITEM==========
export const DELETE_FROM_WHISHLIST ="DELETE_FROM_WHISHLIST" 
export const DELETE_FROM_WHISHLIST_SUCCESS ="DELETE_FROM_WHISHLIST_SUCCESS" 
export const DELETE_FROM_WHISHLIST_FAILURE ="DELETE_FROM_WHISHLIST_FAILURE" 

//================================ DELETE WHISHLIST ITEM==========
export const GET_WHISHLIST ="GET_WHISHLIST" 
export const GET_WHISHLIST_SUCCESS ="GET_WHISHLIST_SUCCESS" 
export const GET_WHISHLIST_FAILURE ="GET_WHISHLIST_FAILURE" 