export const GET_BLOGS_DATA = "GET_BLOGS_DATA";
export const GET_BLOGS_DATA_SUCCESS = "GET_BLOGS_DATA_SUCCESS";
export const GET_BLOGS_DATA_FAILURE = "GET_BLOGS_DATA_FAILURE";

export const GET_SINGLE_BLOG_DATA = "GET_SINGLE_BLOG_DATA";
export const GET_SINGLE_BLOG_DATA_SUCCESS = "GET_SINGLE_BLOG_DATA_SUCCESS";
export const GET_SINGLE_BLOG_DATA_FAILURE = "GET_SINGLE_BLOG_DATA_FAILURE";
