export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS";
export const GET_ALL_REVIEWS_SUCCESS = "GET_ALL_REVIEWS_SUCCESS";
export const GET_ALL_REVIEWS_FAILURE = "GET_ALL_REVIEWS_FAILURE";

//====================ADD REVIEW ON PRODUCT
export const ADD_PRODUCT_REVIEW = "ADD_PRODUCT_REVIEW";
export const ADD_PRODUCT_REVIEW_SUCCESS = "ADD_PRODUCT_REVIEW_SUCCESS";
export const ADD_PRODUCT_REVIEW_FAILURE = "ADD_PRODUCT_REVIEW_FAILURE";

//====================DEL REVIEW ON PRODUCT
export const DELETE_PRODUCT_REVIEW = "DELETE_PRODUCT_REVIEW";
export const DELETE_PRODUCT_REVIEW_SUCCESS = "DELETE_PRODUCT_REVIEW_SUCCESS";
export const DELETE_PRODUCT_REVIEW_FAILURE = "DELETE_PRODUCT_REVIEW_FAILURE";

//====================UPDATE REVIEW ON PRODUCT
export const UPDATE_PRODUCT_REVIEW = "UPDATE_PRODUCT_REVIEW";
export const UPDATE_PRODUCT_REVIEW_SUCCESS = "UPDATE_PRODUCT_REVIEW_SUCCESS";
export const UPDATE_PRODUCT_REVIEW_FAILURE = "UPDATE_PRODUCT_REVIEW_FAILURE";
