export const GET_HERO_DATA = "GET_HERO_DATA";
export const GET_HERO_DATA_SUCCESS = "GET_HERO_DATA_SUCCESS";
export const GET_HERO_DATA_FAILURE = "GET_HERO_DATA_FAILURE";

//============== ABOUT PAGE 

export const GET_ABOUT_DATA = "GET_ABOUT_DATA";
export const GET_ABOUT_DATA_SUCCESS = "GET_ABOUT_DATA_SUCCESS";
export const GET_ABOUT_DATA_FAILURE = "GET_ABOUT_DATA_FAILURE";