export const GET_ALL_ADDREESSES = "GET_ALL_ADDREESSES";
export const GET_ALL_ADDREESSES_SUCCESS = "GET_ALL_ADDREESSES_SUCCESS";
export const GET_ALL_ADDREESSES_FAILURE = "GET_ALL_ADDREESSES_FAILURE";
