export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE";

//===================== GET FINGLE PRODUCT

export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAILURE = "GET_SINGLE_PRODUCT_FAILURE";

//===================== GET PRODUCT BY CATEGORY

export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const GET_PRODUCT_BY_CATEGORY_SUCCESS =
  "GET_PRODUCT_BY_CATEGORY_SUCCESS";
export const GET_PRODUCT_BY_CATEGORY_FAILURE =
  "GET_PRODUCT_BY_CATEGORY_FAILURE";

//===================== GET PRODUCT BY BRAND

export const GET_PRODUCT_BY_BRAND = "GET_PRODUCT_BY_BRAND";
export const GET_PRODUCT_BY_BRAND_SUCCESS = "GET_PRODUCT_BY_BRAND_SUCCESS";
export const GET_PRODUCT_BY_BRAND_FAILURE = "GET_PRODUCT_BY_BRAND_FAILURE";
