export const GET_PRODUCTS_CART = "GET_PRODUCTS_CART";
export const GET_PRODUCTS_CART_SUCCESS = "GET_PRODUCTS_CART_SUCCESS";
export const GET_PRODUCTS_CART_FAILURE = "GET_PRODUCTS_CART_FAILURE";

//==============================
export const ADD_PRODUCTS_CART = "ADD_PRODUCTS_CART";
export const ADD_PRODUCTS_CART_SUCCESS = "ADD_PRODUCTS_CART_SUCCESS";
export const ADD_PRODUCTS_CART_FAILURE = "ADD_PRODUCTS_CART_FAILURE";

//==============================
export const UPDATE_PRODUCT_CONTATY = "UPDATE_PRODUCT_CONTATY";
export const UPDATE_PRODUCT_CONTATY_SUCCESS = "UPDATE_PRODUCT_CONTATY_SUCCESS";
export const UPDATE_PRODUCT_CONTATY_FAILURE = "UPDATE_PRODUCT_CONTATY_FAILURE";

//==============================
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";
export const DELETE_PRODUCT_CART_SUCCESS = "DELETE_PRODUCT_CART_SUCCESS";
export const DELETE_PRODUCT_CART_FAILURE = "DELETE_PRODUCT_CART_FAILURE";

//==============================
export const CLEAR_PRODUCT_CART = "CLEAR_PRODUCT_CART";
export const CLEAR_PRODUCT_CART_SUCCESS = "CLEAR_PRODUCT_CART_SUCCESS";
export const CLEAR_PRODUCT_CART_FAILURE = "CLEAR_PRODUCT_CART_FAILURE";
